version: "3.0"
services:
  
  web:
    image: hello-brunch
    build: .
    ports:
      - "80:80"
    volumes:
      - "html/:/usr/share/nginx/html"
    logging:
      driver: fluentd
      options:
        fluentd-address: "10.250.1.5:24224"
