version: "3.0"
services:
  
  web:
    image: hello-brunch
    build: .
    ports:
      - "80:80"
    logging:
      driver: loki
      options:
        syslog-address: "http://10.250.1.5:5000/loki/api/v1/push"
